version: '3.7'

services:
  web:
    image: nginx:alpine
    container_name: twin_racer_web
    volumes:
      - ./www:/usr/share/nginx/html:ro
    networks:
      - webnet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`racer.twinfinace.io`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
  
  traefik:
    image: traefik:v2.9
    container_name: traefik_proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=stockmaster0x@twinfinance.io"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - webnet
    restart: always

networks:
  webnet:
